name: CI - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  backend-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Backend Dependencies
        run: |
          cd app/backend
          pip install -r requirements.txt

      - name: Run Backend Basic Test
        run: |
          cd app/backend
          python -c "import app.main; print('Backend OK ✅')"

