name: CI - Build, Test & SonarQube Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  backend-test-sonar:
    name: Backend Test + Sonar Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Backend Dependencies
        run: |
          cd app/backend
          pip install -r requirements.txt

      - name: Run Backend Basic Test
        run: |
          cd app/backend
          python -c "import app.main; print('Backend OK ✅')"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=three-tier-devops
            -Dsonar.sources=app/backend

      - name: Build Backend Docker Image
        run: |
          docker build -t three-tier-backend:latest app/backend

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: three-tier-backend:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
          trivyignore: .trivyignore

      

